# A map for advarserial coverage environment

n_agents: 4
n_preys:  8

obstacles_location: []  # specified location of obstacles in the grid
agents_placement:   []  # if random_placement is False, location can be specified
preys_placement:    []  # if random_placement is False, location can be specified

toroidal: False         # whether the world is bounded (False) or toroidal (True)
world_shape: [10, 10]   # the shape of the grid-world [height, width]