# --- "Pseudo-Sequential" parameters ---
name: "pseq"

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0            # Initial epsilon for exploration
epsilon_finish: 0.05          # Final epsilon for exploration
epsilon_anneal_time: 50000    # Number of time steps until exploration has finished

# specify learner, controller and agent
agent: "rnn"                  # A RNN agent that returns its hidden state instead of its value # TODO select architecture
agent_output_type: "q"        # The output format is Q-values
learner: "pseq_learner"       # The learner for PSeq
mac: "pseq"                   # The multi-agent controller for PSeq
mixer:                        # No mixing network for PSeq
mixing_embed_dim: 32          # Hidden dimensions of the state dependent bias function of DCG-V
target_update_interval: 200   # Update the target network every {} episodes

# PSeq-specific configuration
random_ordering: True