
map: "Connected_Areas3" # "Random_Map3" # "Connected_Areas2"

test_nepisode: 1000
episode_limit: 100        # maximum number of time steps per episode

threat_levels: 4          # No. tiers of threats
max_density: 4            # Maximal ratio between robots and area cells in the initial allocation
graph_function: "OPTIMIZED"  # "ORIGIN" for RoiECAI16; "SURV" for the fixed heuristic; "OPTIMIZED" for the optimization criteria heuristic

optim_alpha: 0.1         # Value of alpha of optimization criteria (E[X] - alpha * [T])